/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aol.source;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.MongoClient;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Neha
 */
public class CreateNewCousePanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewCousePanel
     * @param pareFrame
     */
    public CreateNewCousePanel(JFrame pareFrame) {
        initComponents();
        this.calendarOkButton.setVisible(false);
        this.calendarPanel.setVisible(false);
        this.parentFrame=pareFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        courseTypeComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        facultyNameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        venueTextArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        dateTextField = new javax.swing.JTextField();
        calendarOkButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        amtToBeCollectedTextField = new javax.swing.JTextField();
        calendarPanel = new de.wannawork.jcalendar.JCalendarPanel();
        jLabel6 = new javax.swing.JLabel();
        courseIdTextField = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Course Type:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, 25));

        courseTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---Select---","YES+!", "DSN", "Advance Meditation Program", "Sahaj Samadhi Meditation" }));
        courseTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseTypeComboBoxActionPerformed(evt);
            }
        });
        add(courseTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 30, 280, 25));

        jLabel3.setText("Faculty Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, 25));
        add(facultyNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 280, -1));

        jLabel4.setText("Venue:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 69, 22));

        venueTextArea.setColumns(20);
        venueTextArea.setRows(5);
        jScrollPane1.setViewportView(venueTextArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 116, 280, 46));

        jLabel2.setText("Date:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 69, -1));

        dateTextField.setEditable(false);
        dateTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dateTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dateTextFieldFocusLost(evt);
            }
        });
        dateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextFieldActionPerformed(evt);
            }
        });
        add(dateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 174, 91, -1));

        calendarOkButton.setText("OK");
        calendarOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarOkButtonActionPerformed(evt);
            }
        });
        add(calendarOkButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 173, -1, -1));

        jLabel5.setText("Amt.:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 177, -1, -1));
        add(amtToBeCollectedTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 174, 97, -1));

        calendarPanel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                calendarPanelStateChanged(evt);
            }
        });
        calendarPanel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                calendarPanelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                calendarPanelFocusLost(evt);
            }
        });
        add(calendarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 202, -1, -1));

        jLabel6.setText("Course ID:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 214, -1, -1));

        courseIdTextField.setEditable(false);
        add(courseIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 211, 73, -1));

        createButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        createButton.setForeground(new java.awt.Color(0, 153, 255));
        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        add(createButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 249, -1, -1));

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 283, 73, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void dateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTextFieldActionPerformed

    private void calendarPanelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_calendarPanelFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_calendarPanelFocusGained

    private void calendarPanelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_calendarPanelFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_calendarPanelFocusLost

    private void calendarOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarOkButtonActionPerformed
        // TODO add your handling code here:
        Date date = this.calendarPanel.getDate();
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        String format = df.format(date);
        this.dateTextField.setText(format);
        this.calendarPanel.setVisible(false);
        this.calendarOkButton.setVisible(false);
        this.courseIdTextField.setText(this.courseID.append(format).toString());
    }//GEN-LAST:event_calendarOkButtonActionPerformed

    private void dateTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateTextFieldFocusGained
        this.calendarOkButton.setVisible(true);
        this.calendarPanel.setVisible(true);
    }//GEN-LAST:event_dateTextFieldFocusGained

    private void dateTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateTextFieldFocusLost
        this.calendarOkButton.setVisible(false);
        this.calendarPanel.setVisible(false);
    }//GEN-LAST:event_dateTextFieldFocusLost

    private void calendarPanelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_calendarPanelStateChanged
        // TODO add your handling code here:
        Date date = this.calendarPanel.getDate();
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        String format = df.format(date);
        this.dateTextField.setText(format);
    }//GEN-LAST:event_calendarPanelStateChanged

    public void resetAll(){
        this.courseTypeComboBox.setSelectedIndex(0);
        this.facultyNameTextField.setText("");
        this.venueTextArea.setText("");
        this.dateTextField.setText("");
        this.courseIdTextField.setText("");
    }
    
    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
        if(this.courseType==null
                ||this.facultyNameTextField.getText().equals("")
                ||this.venueTextArea.getText().equals("")
                ||this.dateTextField.getText().equals("")
                ||this.courseIdTextField.getText().equals("")){
            JOptionPane.showMessageDialog(parentFrame, "One Or More Fields Empty!");
        }
        else{
            try(MongoClient mongoClient=new MongoClient("localhost",27017)){
                DB db=mongoClient.getDB("AOLReg");
                DBCollection dBCollection = db.getCollection("CurrentCourses");
                BasicDBObject basicDBObject=new BasicDBObject("CourseType",this.courseType)
                        .append("Faculty Name", this.facultyNameTextField.getText())
                        .append("Venue", this.venueTextArea.getText())
                        .append("Date", this.dateTextField.getText())
                        .append("Amount", this.amtToBeCollectedTextField.getText())
                        .append("CourseID", this.courseIdTextField.getText());
                dBCollection.insert(basicDBObject);
                JOptionPane.showMessageDialog(parentFrame, "New "+this.courseTypeComboBox.getSelectedItem()+" Created!");
                this.resetAll();
            }catch(Exception e){
                JOptionPane.showMessageDialog(parentFrame, e);
            }
        }
    }//GEN-LAST:event_createButtonActionPerformed

    private void courseTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseTypeComboBoxActionPerformed
        // TODO add your handling code here:
        switch(this.courseTypeComboBox.getSelectedItem().toString()){
            case "YES+!":
                this.courseType="YES+!";
                this.courseID=new StringBuffer("YESPlus_");
                break;
                
            case "DSN":
                this.courseType="DSN";
                this.courseID=new StringBuffer("DSN_");
                break;
                
            case "Advance Meditation Program":
                this.courseType="Advance Meditation Program";
                this.courseID=new StringBuffer("Adv_");
                break;
                
            case "Sahaj Samadhi Meditation":
                this.courseType="Sahaj Samadhi Meditation";
                this.courseID=new StringBuffer("Sahaj_");
                break;
                
            default:
                this.courseType=null;
                break;
        }
    }//GEN-LAST:event_courseTypeComboBoxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.resetAll();
    }//GEN-LAST:event_jButton2ActionPerformed

    private JFrame parentFrame=null;
    private String courseType=null;
    private StringBuffer courseID=null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amtToBeCollectedTextField;
    private javax.swing.JButton calendarOkButton;
    private de.wannawork.jcalendar.JCalendarPanel calendarPanel;
    private javax.swing.JTextField courseIdTextField;
    private javax.swing.JComboBox courseTypeComboBox;
    private javax.swing.JButton createButton;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JTextField facultyNameTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea venueTextArea;
    // End of variables declaration//GEN-END:variables
}
