/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aol.source;

import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Kaushal
 */
@SuppressWarnings("makefinal")
public class OptionPage extends javax.swing.JFrame {

    /**
     * Creates new form OptionPage
     */
    public OptionPage() {
        initComponents();
        this.panelArrayList=new ArrayList<>();
        buttonGroup = new ButtonGroup();
        buttonGroup.add(fillFormRadioButton);
        buttonGroup.add(registrationStatusRadioButton);
        buttonGroup.add(createCourseButton);
        buttonGroup.add(finalizeCourseRadioButton);
        buttonGroup.add(viewPreviousCoursesRadioButton);
        buttonGroup.add(viewPreviousParticipantsRadioButton);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    private void hideOtherPanels(){
         Iterator<JPanel> itr=this.panelArrayList.iterator();
         while(itr.hasNext()){
            itr.next().setVisible(false);
            System.gc();
         }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mailPanel = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        fillFormRadioButton = new javax.swing.JRadioButton();
        registrationStatusRadioButton = new javax.swing.JRadioButton();
        createCourseButton = new javax.swing.JRadioButton();
        finalizeCourseRadioButton = new javax.swing.JRadioButton();
        viewPreviousParticipantsRadioButton = new javax.swing.JRadioButton();
        viewPreviousCoursesRadioButton = new javax.swing.JRadioButton();
        logOutButton = new javax.swing.JButton();
        panelsLoadHere = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fillFormRadioButton.setText("Fill the Form");
        fillFormRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillFormRadioButtonActionPerformed(evt);
            }
        });

        registrationStatusRadioButton.setText("Registration Status");
        registrationStatusRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationStatusRadioButtonActionPerformed(evt);
            }
        });

        createCourseButton.setText("Create New Course");
        createCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCourseButtonActionPerformed(evt);
            }
        });

        finalizeCourseRadioButton.setText("Finalize Course");
        finalizeCourseRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizeCourseRadioButtonActionPerformed(evt);
            }
        });

        viewPreviousParticipantsRadioButton.setText("View Previous Participants");
        viewPreviousParticipantsRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPreviousParticipantsRadioButtonActionPerformed(evt);
            }
        });

        viewPreviousCoursesRadioButton.setText("View Previous Courses");
        viewPreviousCoursesRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPreviousCoursesRadioButtonActionPerformed(evt);
            }
        });

        logOutButton.setText("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewPreviousCoursesRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewPreviousParticipantsRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(createCourseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(registrationStatusRadioButton)
                                    .addComponent(fillFormRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(finalizeCourseRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(15, 15, 15))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(logOutButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logOutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(fillFormRadioButton)
                .addGap(18, 18, 18)
                .addComponent(registrationStatusRadioButton)
                .addGap(18, 18, 18)
                .addComponent(createCourseButton)
                .addGap(18, 18, 18)
                .addComponent(finalizeCourseRadioButton)
                .addGap(18, 18, 18)
                .addComponent(viewPreviousParticipantsRadioButton)
                .addGap(18, 18, 18)
                .addComponent(viewPreviousCoursesRadioButton)
                .addContainerGap())
        );
        jLayeredPane1.setLayer(fillFormRadioButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(registrationStatusRadioButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(createCourseButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(finalizeCourseRadioButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(viewPreviousParticipantsRadioButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(viewPreviousCoursesRadioButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(logOutButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelsLoadHereLayout = new javax.swing.GroupLayout(panelsLoadHere);
        panelsLoadHere.setLayout(panelsLoadHereLayout);
        panelsLoadHereLayout.setHorizontalGroup(
            panelsLoadHereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2463, Short.MAX_VALUE)
        );
        panelsLoadHereLayout.setVerticalGroup(
            panelsLoadHereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2282, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mailPanelLayout = new javax.swing.GroupLayout(mailPanel);
        mailPanel.setLayout(mailPanelLayout);
        mailPanelLayout.setHorizontalGroup(
            mailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelsLoadHere, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mailPanelLayout.setVerticalGroup(
            mailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mailPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(mailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelsLoadHere))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fillFormRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillFormRadioButtonActionPerformed
        // TODO add your handling code here:
        this.hideOtherPanels();
        ApplicationFormPanel applicationFormPanel =new ApplicationFormPanel(this);
        applicationFormPanel.setBounds(0, 0, this.panelsLoadHere.getWidth(),this.panelsLoadHere.getHeight());
        this.panelsLoadHere.add(applicationFormPanel);
        applicationFormPanel.setVisible(true);
        this.panelArrayList.add(applicationFormPanel);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_fillFormRadioButtonActionPerformed

    private void registrationStatusRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationStatusRadioButtonActionPerformed
        // TODO add your handling code here:
        this.hideOtherPanels();
        RegistrationStatusPanel registrationStatusPanel =new RegistrationStatusPanel(this);
        registrationStatusPanel.setBounds(0, 0, this.panelsLoadHere.getWidth(),this.panelsLoadHere.getHeight());
        this.panelsLoadHere.add(registrationStatusPanel);
        registrationStatusPanel.setVisible(true);
        this.panelArrayList.add(registrationStatusPanel);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_registrationStatusRadioButtonActionPerformed

    private void createCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCourseButtonActionPerformed
    // TODO add your handling code here:
        this.hideOtherPanels();
        CreateNewCousePanel createNewCousePanel =new CreateNewCousePanel(this);
        createNewCousePanel.setBounds(0, 0, this.panelsLoadHere.getWidth(),this.panelsLoadHere.getHeight());
        this.panelsLoadHere.add(createNewCousePanel);
        createNewCousePanel.setVisible(true);
        this.panelArrayList.add(createNewCousePanel);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_createCourseButtonActionPerformed

    private void finalizeCourseRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizeCourseRadioButtonActionPerformed
        // TODO add your handling code here:
        this.hideOtherPanels();
        FinalizeCoursePanel finalizeCoursePanel =new FinalizeCoursePanel(this);
        finalizeCoursePanel.setBounds(0, 0, this.panelsLoadHere.getWidth(),this.panelsLoadHere.getHeight());
        this.panelsLoadHere.add(finalizeCoursePanel);
        finalizeCoursePanel.setVisible(true);
        this.panelArrayList.add(finalizeCoursePanel);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_finalizeCourseRadioButtonActionPerformed

    private void viewPreviousCoursesRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPreviousCoursesRadioButtonActionPerformed
        // TODO add your handling code here:
        this.hideOtherPanels();
        ViewPreviousCourses previousCourses =new ViewPreviousCourses();
        previousCourses.setBounds(0, 0, this.panelsLoadHere.getWidth(),this.panelsLoadHere.getHeight());
        this.panelsLoadHere.add(previousCourses);
        previousCourses.setVisible(true);
        this.panelArrayList.add(previousCourses);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_viewPreviousCoursesRadioButtonActionPerformed

    private void viewPreviousParticipantsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPreviousParticipantsRadioButtonActionPerformed
        // TODO add your handling code here:
        this.hideOtherPanels();
        ViewPreviousParticipants previousParticipants =new ViewPreviousParticipants();
        previousParticipants.setBounds(0, 0, this.panelsLoadHere.getWidth(),this.panelsLoadHere.getHeight());
        this.panelsLoadHere.add(previousParticipants);
        previousParticipants.setVisible(true);
        this.panelArrayList.add(previousParticipants);
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_viewPreviousParticipantsRadioButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        // TODO add your handling code here:
        LoginFrame loginFrame=new LoginFrame();
        loginFrame.setVisible(true);
        this.setVisible(false);
        this.dispose();    
    }//GEN-LAST:event_logOutButtonActionPerformed

    /**
     * @param args the command line arguments
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionPage().setVisible(true);
            }
        });
    }*/
    
    private ArrayList <JPanel> panelArrayList=null;
    private ButtonGroup buttonGroup=null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton createCourseButton;
    private javax.swing.JRadioButton fillFormRadioButton;
    private javax.swing.JRadioButton finalizeCourseRadioButton;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton logOutButton;
    private javax.swing.JPanel mailPanel;
    private javax.swing.JLayeredPane panelsLoadHere;
    private javax.swing.JRadioButton registrationStatusRadioButton;
    private javax.swing.JRadioButton viewPreviousCoursesRadioButton;
    private javax.swing.JRadioButton viewPreviousParticipantsRadioButton;
    // End of variables declaration//GEN-END:variables
}
