/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aol.source;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.MongoClient;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author BaZinGa
 */
public class RegistrationForm extends javax.swing.JPanel {

    /**
     * Creates new form RegistrationForm
     * @param previousPanel
     * @param parentFrame
     */
    public RegistrationForm(JPanel previousPanel,JFrame parentFrame){
        initComponents();
        this.previousPanel=previousPanel;
        this.parentFrame=parentFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FirstNameLabel = new javax.swing.JLabel();
        FirstNameTextField = new javax.swing.JTextField();
        Password1Label = new javax.swing.JLabel();
        Password1TextField = new javax.swing.JPasswordField();
        Password2Label = new javax.swing.JLabel();
        Password2TextField = new javax.swing.JPasswordField();
        SubmitButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FirstNameLabel.setText("Username:");
        add(FirstNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 70, 20));

        FirstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameTextFieldActionPerformed(evt);
            }
        });
        add(FirstNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 162, -1));

        Password1Label.setText("Enter new Password:");
        add(Password1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        Password1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password1TextFieldActionPerformed(evt);
            }
        });
        add(Password1TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 163, -1));

        Password2Label.setText("Confirm Password:");
        add(Password2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));
        add(Password2TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 163, -1));

        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        add(SubmitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });
        add(ResetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        backButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backButton.setText("<");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void FirstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameTextFieldActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        String fname,pass1,pass2;
        fname=FirstNameTextField.getText();
        pass1=Password1TextField.getText();
        pass2=Password2TextField.getText();
        if(fname.equals("")|| pass1.equals("") || pass2.equals(""))
        {
            JOptionPane.showMessageDialog(parentFrame, "All fields are mandatory");
            return;
        }
        else
        {
            if(pass1.equals(pass2))
            {
                
                try(MongoClient mongoClient=new MongoClient("localhost",27017)){
                    DB db=mongoClient.getDB("AOLReg");
                    DBCollection coll=db.getCollection("VolunteerLogin");
                    BasicDBObject doc=new BasicDBObject("username",fname );
                    try(DBCursor bCursor=coll.find(doc)){
                        if(bCursor.hasNext()){
                            JOptionPane.showMessageDialog(parentFrame, "Username Already Taken!");
                            return;
                        }
                    }
                    doc.append("password",pass1);
                    coll.insert(doc);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(parentFrame, "Entered passwords do not match");
                return;
            }
        }
        JOptionPane.showMessageDialog(this, "Registered Sussessfully!");       
        FirstNameTextField.setText("") ;
        Password1TextField.setText("");
        Password2TextField.setText("");
        this.goBack();

        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        FirstNameTextField.setText("") ;
        Password1TextField.setText("");
        Password2TextField.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void Password1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password1TextFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.goBack();
    }//GEN-LAST:event_backButtonActionPerformed

    public void goBack(){
        this.setVisible(false);
        this.previousPanel.setVisible(true);
        this.parentFrame.revalidate();
        this.repaint();
    }
    
    private final JPanel previousPanel;
    private final JFrame parentFrame;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField FirstNameTextField;
    private javax.swing.JLabel Password1Label;
    private javax.swing.JPasswordField Password1TextField;
    private javax.swing.JLabel Password2Label;
    private javax.swing.JPasswordField Password2TextField;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JButton backButton;
    // End of variables declaration//GEN-END:variables
}
