/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aol.source;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import com.mongodb.MongoClient;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BaZinGa
 */
public class ViewPreviousCourses extends javax.swing.JPanel {

    /**
     * Creates new form ViewPreviousCourses
     */
    public ViewPreviousCourses() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        courseTypeComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        multiPTable = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Course Type");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 14, -1, -1));

        courseTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---Select---","YES+!", "DSN", "Advance Meditation Program", "Sahaj Samadhi Meditation" }));
        courseTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseTypeComboBoxActionPerformed(evt);
            }
        });
        add(courseTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 11, 242, -1));

        multiPTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        multiPTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiPTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(multiPTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 49, 730, 477));
    }// </editor-fold>//GEN-END:initComponents

    private void courseTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseTypeComboBoxActionPerformed
        // TODO add your handling code here:
        if(this.courseTypeComboBox.getSelectedIndex()!=0){
            String column[]={"CourseType","Faculty Name","Venue","Date","Amount","CourseID"};
            DefaultTableModel defaultTableModel=new DefaultTableModel(column, 0);
            try(MongoClient mongoClient=new MongoClient("localhost",27017)){
                DB db=mongoClient.getDB("AOLReg");
                DBCollection dbCollection=db.getCollection("AllPreviousCourses");
                BasicDBObject basicDBObject=new BasicDBObject("CourseType",this.courseTypeComboBox.getSelectedItem().toString());
                try(DBCursor dBCursor=dbCollection.find(basicDBObject)){
                    while(dBCursor.hasNext()){
                        DBObject dBObject=dBCursor.next();
                        String courseType=dBObject.get("CourseType").toString();
                        String faculty_Name=dBObject.get("Faculty Name").toString();
                        String Venue=dBObject.get("Venue").toString();
                        String Date=dBObject.get("Date").toString();
                        String Amount=dBObject.get("Amount").toString();
                        String courseID=dBObject.get("CourseID").toString();
                        defaultTableModel.addRow(new Object[]{courseType,faculty_Name,Venue,Date,Amount,courseID});
                    }
                }
                this.multiPTable.setModel(defaultTableModel);
            }
        }
    }//GEN-LAST:event_courseTypeComboBoxActionPerformed

    private void multiPTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiPTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_multiPTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox courseTypeComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable multiPTable;
    // End of variables declaration//GEN-END:variables
}
